#!/usr/bin/env python3
"""One-time live recorder for P4B-1's raw Tiingo client fixtures.

This is a **recording tool, not shipped package code and not a test**: it is
never imported by ``smart_beta`` and it lives outside ``tests/`` so pytest
never collects it. Run it once, by hand, with a real key in the environment:

    TIINGO_API_KEY=... .venv/bin/python scripts/fetch_tiingo_fixtures.py

It writes each Tiingo response body *verbatim* to
``tests/fixtures/tiingo/client/<name>.json`` and records the request path and
HTTP status for each in ``manifest.json`` (the one non-200 specimen is RGEN's
fundamentals call, which is expected to return 400 under the current plan).
The API key is read only from the environment and is never written to disk.

Wave 2+ tasks can reuse this same technique for their own fixture
subdirectories: point ``--out`` at ``tests/fixtures/tiingo/<task>/`` and edit
``_specs`` below.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Callable

# Make the repository importable when run as a plain script from anywhere.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from smart_beta.vendors.tiingo.client import (  # noqa: E402
    API_KEY_ENV_VAR,
    TiingoAPIError,
    TiingoClient,
)

DEFAULT_OUT_DIR = REPO_ROOT / "tests" / "fixtures" / "tiingo" / "client"

# (body filename, request path, call)
Spec = tuple[str, str, Callable[[TiingoClient], object]]


def _specs() -> list[Spec]:
    return [
        (
            "aapl_eod_prices_2020-08-20_2020-09-05.json",
            "/tiingo/daily/AAPL/prices",
            lambda client: client.get_eod_prices("AAPL", "2020-08-20", "2020-09-05"),
        ),
        (
            "aapl_meta.json",
            "/tiingo/daily/AAPL",
            lambda client: client.get_meta("AAPL"),
        ),
        (
            "twtr_meta.json",
            "/tiingo/daily/TWTR",
            lambda client: client.get_meta("TWTR"),
        ),
        (
            "aapl_fundamentals_asreported.json",
            "/tiingo/fundamentals/AAPL/statements",
            lambda client: client.get_fundamentals_asreported(
                "AAPL", "2026-01-01", "2026-12-31"
            ),
        ),
        (
            "aapl_fundamentals_normalized.json",
            "/tiingo/fundamentals/AAPL/statements",
            lambda client: client.get_fundamentals_normalized(
                "AAPL", "2026-01-01", "2026-12-31"
            ),
        ),
        (
            "rgen_fundamentals_asreported_error.json",
            "/tiingo/fundamentals/RGEN/statements",
            lambda client: client.get_fundamentals_asreported("RGEN"),
        ),
    ]


def record(
    client: TiingoClient, call: Callable[[TiingoClient], object]
) -> tuple[int, object]:
    """Run one call and return ``(status_code, body)``. A non-200 response is
    captured as data (via ``TiingoAPIError``), not treated as a script error --
    the failing RGEN specimen is a required recording."""
    try:
        return 200, call(client)
    except TiingoAPIError as exc:
        return exc.status_code, exc.body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help=f"fixture output directory (default: {DEFAULT_OUT_DIR})",
    )
    args = parser.parse_args()

    api_key = os.environ.get(API_KEY_ENV_VAR)
    if not api_key:
        print(
            f"error: {API_KEY_ENV_VAR} is not set. This recorder needs a real "
            "Tiingo key; it never logs or writes the key itself.",
            file=sys.stderr,
        )
        return 2

    args.out.mkdir(parents=True, exist_ok=True)
    client = TiingoClient(api_key=api_key)

    manifest: dict[str, object] = {
        "_comment": (
            "Generated by scripts/fetch_tiingo_fixtures.py from live Tiingo "
            "responses. Each entry maps a raw response body file (verbatim "
            "Tiingo JSON, no wrapper) to the url_path that produced it and the "
            "HTTP status code observed."
        ),
        "recordings": {},
    }
    recordings = manifest["recordings"]
    assert isinstance(recordings, dict)

    for filename, path, call in _specs():
        print(f"GET {path} -> {filename}", flush=True)
        status, body = record(client, call)
        (args.out / filename).write_text(json.dumps(body, indent=2) + "\n")
        recordings[filename] = {"url_path": path, "status_code": status}
        print(f"  status {status}")

    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {len(recordings)} recordings + manifest.json to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
